# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

options = webdriver.ChromeOptions()
options.add_experimental_option("detach", True)
class TestRec1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_rec1(self):
    self.driver.get("https://www.99acres.com/")
    self.driver.fullscreen_window()
    self.driver.execute_script("window.scrollTo(0,37)")
    self.driver.execute_script("window.scrollTo(0,2084)")
    self.driver.execute_script("window.scrollTo(0,3923)")
    self.driver.execute_script("window.scrollTo(0,5518)")
    self.driver.execute_script("window.scrollTo(0,6330)")
    self.driver.execute_script("window.scrollTo(0,7228)")
    self.driver.execute_script("window.scrollTo(0,8024)")
    self.driver.execute_script("window.scrollTo(0,8826)")
    self.driver.execute_script("window.scrollTo(0,9741)")
    self.driver.execute_script("window.scrollTo(0,10596)")
    self.driver.execute_script("window.scrollTo(0,0)")
    wait = WebDriverWait(self.driver, 3)
    element = wait.until(EC.presence_of_all_elements_located((By.ID, "keyword2")))
    a = self.driver.find_element(By.ID, "keyword2")
    self.driver.find_element(By.ID, "keyword2").click()
    self.driver.find_element(By.ID, "bedroom_num_wrap").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'3\']/span[2]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'2\']/span[2]").click()
    self.driver.find_element(By.ID, "keyword2").click()
    self.driver.find_element(By.ID, "keyword2").send_keys("Mumbai")
    self.driver.find_element(By.CSS_SELECTOR, ".inPageSearchBox__searchBtn span").click()
    
    
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.fullscreen_window()
  #  wait = WebDriverWait(self.driver, 3) # 3 second timeout
    element = wait.until(EC.presence_of_all_elements_located((By.ID, "srp_tuple_property_title")))


    self.driver.find_element(By.XPATH, "//a[@id=\'srp_tuple_property_title\']/h2").click()
    self.vars["win3277"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win3277"])

    try:
      society_reviews_element = self.driver.find_element(By.LINK_TEXT, "Society Reviews")
      society_reviews_element.click()
      self.driver.execute_script("arguments[0].scrollIntoView();", society_reviews_element)
    except NoSuchElementException:
      explore_locality_element = self.driver.find_element(By.LINK_TEXT, "Explore Locality")
      explore_locality_element.click()
      self.driver.execute_script("arguments[0].scrollIntoView();", explore_locality_element)
    #self.driver.execute_script("window.scrollTo(0,87)")
    #self.driver.execute_script("window.scrollTo(0,300)")
    #self.driver.close()
    #self.driver.switch_to.window(self.vars["root"])
    #self.driver.close()
    while(True):
       pass
    launchBrowser()
  
testClass=TestRec1()

testClass.setup_method("")
testClass.test_rec1()
#testClass.teardown_method("")

